# -*- coding: utf-8 -*-
"""Project_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19GS2lwQoyOOd6JpsTo3amvJdSDjkeiio
"""

import keras

!apt-get install p7zip-full
!unzip -q  kagglecatsanddogs_5340.zip
#IMPORTING LIBRARIES
import numpy as np 
import pandas as pd
import cv2
import tensorflow as tf
import os
import matplotlib.pyplot as plt

#IMPORTING DATASET

img = []
label = []
for i in os.listdir("PetImages"):
  for j in os.listdir("PetImages/"+i):
    if i ==  "Cat":
      label.append(0)
    else:
      label.append(1)
    img.append(os.path.join("PetImages",i,j))

#CREATING DATAFRAME
img_df = pd.DataFrame(img)
img_label = pd.DataFrame(label)
df = pd.concat([img_df,img_label],axis=1)
df.columns = ["Image","Label"]
df.head(10)

#DELETING THE FILES WHICH IS NOT AN IMAGE
import PIL
worng = []
for i in df["Image"]:
    try:
        img = PIL.Image.open(i)
    except:
        worng.append(i)
for i in worng:
  df.drop(df[df["Image"] == i].index )

# VISUALIZING WEIGHT
import seaborn as sns
sns.countplot(df["Label"])

#RESIZE
for index,link in enumerate(df["Image"]):
    images = Image.open(link)
    images = images.resize((200,200),Image.ANTIALIAS)

    dir_path = "/content/resi"
    if index in range(0,12502):
      name = "Dog_"+str(index)+".jpg"
    elif index in range(12501,25001):
      name="Cat_"+str(index)+".jpg"
    file_path = os.path.join( dir_path, name  ) 
    images.convert('RGB').save( file_path )

files = os.listdir("/content/resi")
print(files)
img_path_list = []
for f in files:
    if f.endswith(".jpg"): 
        img_path_list.append(f)

#DATA VISUALIZATION
import random
from google.colab.patches import cv2_imshow
for i in range(0,5):
  number=random.randint(0,1000)
  rimg=img_path_list[number]
  print(rimg)
  image=cv2.imread("/content/resi/"+rimg)
  cv2_imshow(image)

#MODELIZATION
from sklearn.model_selection import train_test_split

df['Label'] = df['Label'].astype('str')
train,test = train_test_split(df,test_size=0.33,random_state=5)
train.head()

from keras.preprocessing.image import ImageDataGenerator
train_generator = ImageDataGenerator(
    rescale = 1./255,  
    rotation_range = 40, 
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True,
    fill_mode = 'nearest'
)

val_generator = ImageDataGenerator(rescale = 1./255)

train_iterator = train_generator.flow_from_dataframe(
    train, 
    x_col='Image', 
    y_col='Label', 
    target_size=(128,128), 
    batch_size=512, 
    class_mode='binary'
)

val_iterator = val_generator.flow_from_dataframe(
    test, 
    x_col='Image', 
    y_col='Label', 
    target_size=(128,128), 
    batch_size=512, 
    class_mode='binary'
)
test_images = val_generator.flow_from_dataframe(
    dataframe=df,
    x_col='Image',
    y_col='Label',
    target_size=(128, 128),
    color_mode='rgb',
    class_mode='binary',
    batch_size=32,
    shuffle=False)

from keras import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense
model = Sequential([
                    Conv2D(16, (3,3), activation='relu', input_shape=(128,128,3)),
                    MaxPool2D((2,2)),
                    Conv2D(32, (3,3), activation='relu'),
                    MaxPool2D((2,2)),
                    Conv2D(64, (3,3), activation='relu'),
                    MaxPool2D((2,2)),
                    Flatten(),
                    Dense(512, activation='relu'),
                    Dense(1, activation='sigmoid')
])

#TRAIN AND SCORE SCORE
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()
print("-----------------------------------------------------------------------")
history = model.fit(train_iterator, epochs=10, validation_data=val_iterator)

#HEATMAP
from sklearn.metrics import confusion_matrix, classification_report
pred = (model.predict(test_images) >= 0.5).astype(np.int)

cm = confusion_matrix(test_images.labels, pred, labels=[0, 1])
clr = classification_report(test_images.labels, pred, labels=[0, 1])
                        
LABELS=["Cat", "Dog"]

plt.figure(figsize=(6, 6))
sns.heatmap(cm, annot=True, fmt='g', vmin=0, cmap='Blues', cbar=False)
plt.xticks(ticks=[0.5, 1.5], labels=["Cat", "Dog"])
plt.yticks(ticks=[0.5, 1.5], labels=["Cat", "Dog"])
plt.xlabel("Prediction")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

score = history.history['accuracy']
val_score = history.history['val_accuracy']
epochs = range(len(score))

plt.plot(epochs, score, 'b', label='Training Accuracy')
plt.plot(epochs, val_score, 'r', label='Validation Accuracy')
plt.title('Accuracy Graph')
plt.legend()
plt.figure()

loss = history.history['loss']
val_loss = history.history['val_loss']
plt.plot(epochs, loss, 'b', label='Training Loss')
plt.plot(epochs, val_loss, 'r', label='Validation Loss')
plt.title('Loss Graph')
plt.legend()
plt.show()